port gp to gitconfig

diff --git a/gitconfig b/gitconfig
--- a/gitconfig
+++ b/gitconfig
@@ -102,13 +102,13 @@ whatadded = log --diff-filter=A
 whattouched = log --diff-filter=M
 
 # [L]og [S]earch
-ls = "!f() { \
+ls = "!fzf_git_log() { \
   local format='%C(yellow)%h%C(red)%d%C(reset) - %C(bold green)(%ar)%C(reset) %s %C(blue)<%an>%C(reset)'; \
   local preview='git show --color=always {1}'; \
   git log --color=always --format=\"$format\" $@ | \
     fzf --ansi --no-sort --no-height --reverse --multi --delimiter ' ' --preview \"$preview\" | \
       cut -d ' ' -f1; \
-}; f"
+}; fzf_git_log"
 
 # [B]ranch [D]elete
 bd = "!f() { git branch | fzf --multi | xargs git branch -D; }; f"
@@ -139,3 +139,28 @@ ri = "!git_rebase_i() { \
   local branchpoint=`git merge-base $mainbranch $currbranch`; \
   git rebase -i $branchpoint $currbranch; \
 }; git_rebase_i"
+
+# [P]ush the current branch, confirm master/main push.
+# allow force push unless master/main
+p = "!git_push() { \
+  local nargs=\"$#\"; \
+  local currbranch=`git rev-parse --abbrev-ref HEAD`; \
+  if [ \"$@##*-d*\" ]; then echo \"-d arg not allowed\"; exit 1; fi; \
+  if [ $currbranch = \"HEAD\" ]; then echo \"not on a branch\"; exit 1; fi; \
+  if [ $currbranch = \"master\" ] || [ $currbranch = \"main\" ]; then \
+    echo \"push $currbranch, Are you sure? (y/n)\"; \
+    read REPLY; \
+    if [ $REPLY = \"y\" ] || [ $REPLY = \"Y\" ] ; then \
+      if [ $nargs = 0 ]; then \
+        git push origin $currbranch; \
+      else \
+        echo \"master/main push no args allowed\"; exit 1; \
+      fi;\
+    else \
+      echo \"git push aborted\"; exit 1; \
+    fi;\
+  else \
+    # branch is not master or main. allow args \
+    git push origin $currbranch $@; \
+  fi; \
+}; git_push"
